# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPPapRPpplcIGjvhgAdPWHJOmFeuU6z-
"""

# Commented out IPython magic to ensure Python compatibility.
# %config Completer.use_jedi = False

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

books=pd.read_csv("books.csv")
books.shape

plt.figure(figsize=(8, 5))
sns.heatmap(books.isnull().T, cmap='viridis', cbar=False, yticklabels=books.columns)
plt.title("Missing Values Heatmap")
plt.show()

books['missing_description']=np.where(books['description'].isna(),0,1)
books['age']=2025-books['published_year']

columns_needed=["num_pages",'age','missing_description','average_rating']

correlation_matrix=books[columns_needed].corr(method="spearman")

sns.set_theme(style="dark")

plt.figure(figsize=(8,6))
heatmap=sns.heatmap(correlation_matrix,annot=True,fmt=".2f", cmap="coolwarm",cbar_kws={"label":"Spearman Correlation"})
plt.show()

cleaned_books=books[~(books["description"].isna()) &
                    ~(books["num_pages"].isna())&
                    ~(books["average_rating"].isna())&
                    ~(books["published_year"].isna())
                    ]

cleaned_books["categories"].value_counts().reset_index().sort_values("count",ascending=False)

cleaned_books["length_of_desc"]=cleaned_books['description'].str.split().str.len()

cleaned_books.loc[cleaned_books["length_of_desc"].between(1, 4), "description"]

cleaned_books_25=cleaned_books[cleaned_books["length_of_desc"]>=25]

cleaned_books_25["title_and_subtitle"] = (
    np.where(cleaned_books_25["subtitle"].isna(), cleaned_books_25["title"],
             cleaned_books_25[["title", "subtitle"]].astype(str).agg(": ".join, axis=1))
)

cleaned_books_25["tagged_description"] = cleaned_books_25[["isbn13", "description"]].astype(str).agg(" ".join, axis=1)

(
    cleaned_books_25
    .drop(["subtitle", "missing_description", "age", "length_of_desc"], axis=1)
    .to_csv("books_cleaned.csv", index = False)
)